# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'IOSMovieProj' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IOSMovieProj

  target 'IOSMovieProjTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'IOSMovieProjUITests' do
    # Pods for testing
  end
  
project '/Volumes/In Between/GitHub/IOS-Movie-App-Project/IOSMovieProj/IOSMovieProj.xcodeproj'

pod 'Alamofire', '~> 4.0'
pod 'SwiftyJSON', '~> 4.0'
pod 'SDWebImage', '~> 3.8'
pod 'youtube-ios-player-helper', '~> 0.1.4'
pod 'Cosmos', '~> 21.0'
pod 'SDWebImageYYPlugin/YYCache'

end
